### ISSUE TITLE
i wanna know somthing about of the dateset 

### ISSUE THREAD

**Issue by hpoqe** [Luffy03/DBFNet#1]
Respect shcolar:
                would you mind to share the format of the dateset of Potsdam and Vaihingen in the article.

                                                                                                                                                                Thanks!    
                                                                                                                                                                 HuangPing    XiangTanUniversity

**Comment by Luffy03** [comment]
Thanks for your attention!
We have provided the download link of the datasets in this repo. Please follow the instructions of the 'Getting start' and 'Prepare dataset'. We changed the format from 'tif' to 'png‘, the details of pre-processing are provided in 'DataProcess'.

**Comment by hpoqe** [comment]
I had got the dateset after processing,but i cannot to run this code from the readme file,would you supply some advice,or i must to get the raw dataset from the offical  website

**Comment by Luffy03** [comment]
You don't have to attach the raw dataset. You can directly download our processed dataset for training. 
I cannot understand your problems clearly. Would you please present more details?
Note: you should edit the 'data_root' as your own directory in options.py.

**Comment by hpoqe** [comment]
When i run this instruct --python predict.py   ImportError: cannot import name 'color_dict' from 'datafiles.color_dict
When i run this instruct  --python run/point/p_train.py ModuleNotFoundError: No module named 'options
I donot know this problem,Is there a deaklock or the version of pytorch in my computer is not right?

**Comment by Luffy03** [comment]
This is about the absolute path of your python settings. You can use 'os.path.abspath' or tool 'sys' to solve the problems, which are very low-level. 
You can find 'options' and 'datafiles/color_dict.py' in our repo. 
Or you can directly copy codes in 'options' and 'datafiles/color_dict.py' to 'p_train.py'.

**Comment by Luffy03** [comment]
You can also run 'p_train.py' in pycharm/vscode directly if you do not want to run it on the bash.

**Comment by Luffy03** [comment]
I will close this issue. Feel free to re-open it if you still have any questions.
Many thanks for your attention again!

**Comment by Luffy03** [comment]
I will close this issue. Feel free to re-open it if you still have any questions.
Many thanks for your attention again!
