### ISSUE TITLE
About data processing

### ISSUE THREAD

**Issue by simonep1052** [Luffy03/DBFNet#2]
Hello,

Can you please tell me which original extracted folders from the Potsdam and Vaihingen datasets you used for the following four variables, and explain their meaning?

Potsdam: [`label_path` and `vis_path`](https://github.com/Luffy03/DBFNet/blob/d5eaf8479f90375691d6371e68657417330c4b30/DataProcess/postdam/CropPost.py#L73C5-L74C58). I cannot find `Labels` folder in the extracted files.

Vaihingen: [`label_path` and `vis_path`](https://github.com/Luffy03/DBFNet/blob/d5eaf8479f90375691d6371e68657417330c4b30/DataProcess/vaihingen/CropVai.py#L76C5-L77C55). For this dataset, I cannot see the `vis` folder in the extracted files.

I'm trying to learn from you codes so I can then pre-process my dataset using your code. It would be really helpful if you could clarify this for me. Thank you.

**Comment by USTguy** [comment]
> Hello,
> 
> Can you please tell me which original extracted folders from the Potsdam and Vaihingen datasets you used for the following four variables, and explain their meaning?
> 
> Potsdam: [`label_path` and `vis_path`](https://github.com/Luffy03/DBFNet/blob/d5eaf8479f90375691d6371e68657417330c4b30/DataProcess/postdam/CropPost.py#L73C5-L74C58). I cannot find `Labels` folder in the extracted files.
> 
> Vaihingen: [`label_path` and `vis_path`](https://github.com/Luffy03/DBFNet/blob/d5eaf8479f90375691d6371e68657417330c4b30/DataProcess/vaihingen/CropVai.py#L76C5-L77C55). For this dataset, I cannot see the `vis` folder in the extracted files.
> 
> I'm trying to learn from you codes so I can then pre-process my dataset using your code. It would be really helpful if you could clarify this for me. Thank you.

Hello! You can use 'TransPostLabel.py' to transform original labels to vis_labels. And the vis_labels will be placed in vis_path.
If you want to process your own data, you may need to modify the 'label2color_dict' in the 'value_to_rgb' function.
For original datasets, you may need to download from the original website.

**Comment by simonep1052** [comment]
Thank you so much for your helpful explanation and for taking the time to help me.
